on:
  push:
    branches:
    - main
env:
  group: Grp-ImranCloudRef
jobs:
  Job_1:
  
    name: Agent job 1
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Unit-Test-With-Coverage
      run: cd ${{ github.workspace }}/apigee-cicd-master && npm install && npm test test/unit/test.js && npm run coverage test/unit/test.js
      
    - name: Coverage
      run: cd ${{ github.workspace }}/apigee-cicd-master/coverage && ls 
      
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ${{ github.workspace }}/**/test-results.xml
        
    - name: Coverage
      run: cp ${{ github.workspace }}/apigee-cicd-master/coverage/cobertura-coverage.xml ${{ github.workspace }} && cd ${{ github.workspace }} &&  ls     
      
    - uses: tintef/nyc-reporter-action
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPORTER: 'text' # defaults to 'text-summary'    